/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AjustesRouteImport } from './routes/ajustes'
import { Route as InformeRouteImport } from './routes/informe'
import { Route as RcpRouteImport } from './routes/rcp'
import { Route as TriajeRouteImport } from './routes/triaje'
import { Route as ProtocoloIdRouteImport } from './routes/protocolo.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AjustesRoute = AjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => rootRouteImport,
} as any)
const InformeRoute = InformeRouteImport.update({
  id: '/informe',
  path: '/informe',
  getParentRoute: () => rootRouteImport,
} as any)
const RcpRoute = RcpRouteImport.update({
  id: '/rcp',
  path: '/rcp',
  getParentRoute: () => rootRouteImport,
} as any)
const TriajeRoute = TriajeRouteImport.update({
  id: '/triaje',
  path: '/triaje',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocoloIdRoute = ProtocoloIdRouteImport.update({
  id: '/protocolo/$id',
  path: '/protocolo/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/informe': typeof InformeRoute
  '/rcp': typeof RcpRoute
  '/triaje': typeof TriajeRoute
  '/protocolo/$id': typeof ProtocoloIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/informe': typeof InformeRoute
  '/rcp': typeof RcpRoute
  '/triaje': typeof TriajeRoute
  '/protocolo/$id': typeof ProtocoloIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/informe': typeof InformeRoute
  '/rcp': typeof RcpRoute
  '/triaje': typeof TriajeRoute
  '/protocolo/$id': typeof ProtocoloIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/ajustes' | '/informe' | '/rcp' | '/triaje' | '/protocolo/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ajustes' | '/informe' | '/rcp' | '/triaje' | '/protocolo/$id'
  id:
    | '__root__'
    | '/'
    | '/ajustes'
    | '/informe'
    | '/rcp'
    | '/triaje'
    | '/protocolo/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AjustesRoute: typeof AjustesRoute
  InformeRoute: typeof InformeRoute
  RcpRoute: typeof RcpRoute
  TriajeRoute: typeof TriajeRoute
  ProtocoloIdRoute: typeof ProtocoloIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajustes': {
      id: '/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AjustesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informe': {
      id: '/informe'
      path: '/informe'
      fullPath: '/informe'
      preLoaderRoute: typeof InformeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rcp': {
      id: '/rcp'
      path: '/rcp'
      fullPath: '/rcp'
      preLoaderRoute: typeof RcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/triaje': {
      id: '/triaje'
      path: '/triaje'
      fullPath: '/triaje'
      preLoaderRoute: typeof TriajeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocolo/$id': {
      id: '/protocolo/$id'
      path: '/protocolo/$id'
      fullPath: '/protocolo/$id'
      preLoaderRoute: typeof ProtocoloIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AjustesRoute: AjustesRoute,
  InformeRoute: InformeRoute,
  RcpRoute: RcpRoute,
  TriajeRoute: TriajeRoute,
  ProtocoloIdRoute: ProtocoloIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
